#application: mhsquirecom
#version: 1
runtime: python27
api_version: 1
threadsafe: true

# Handlers match in order, put above the default handler.
handlers:
- url: /css
  static_dir: html/css

- url: /font-awesome
  static_dir: html/font-awesome

- url: /fonts
  static_dir: html/fonts

- url: /img
  static_dir: html/img

- url: /js
  static_dir: html/js

- url: /.*
  script: subroutes.application
  secure: never


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

